# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shapes_pb2 as shapes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x03vsg\x1a\x0cshapes.proto\"\x84\x01\n\x0bRootMessage\x12\x1f\n\tset_shape\x18\x01 \x01(\x0b\x32\n.vsg.ShapeH\x00\x12$\n\x0cset_bg_color\x18\x02 \x01(\x0b\x32\x0c.vsg.BgColorH\x00\x12#\n\x0bset_texture\x18\x03 \x01(\x0b\x32\x0c.vsg.TextureH\x00\x42\t\n\x07\x63ommand\"\x18\n\x07\x42gColor\x12\r\n\x05\x63olor\x18\x01 \x03(\x02\"&\n\x07Texture\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x0c\n\x03vsgB\x03VsgP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\003vsgB\003VsgP\001'
  _ROOTMESSAGE._serialized_start=37
  _ROOTMESSAGE._serialized_end=169
  _BGCOLOR._serialized_start=171
  _BGCOLOR._serialized_end=195
  _TEXTURE._serialized_start=197
  _TEXTURE._serialized_end=235
# @@protoc_insertion_point(module_scope)
