# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shapes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cshapes.proto\x12\x03vsg\"k\n\x05Shape\x12\x1d\n\x06square\x18\x01 \x01(\x0b\x32\x0b.vsg.SquareH\x00\x12\x1d\n\x06\x63ircle\x18\x02 \x01(\x0b\x32\x0b.vsg.CircleH\x00\x12\x1b\n\x05\x63ross\x18\x03 \x01(\x0b\x32\n.vsg.CrossH\x00\x42\x07\n\x05shape\"#\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"5\n\x06Square\x12\x0c\n\x04size\x18\x01 \x01(\x02\x12\x1d\n\x03\x63tr\x18\x02 \x01(\x0b\x32\x10.vsg.Coordinates\"7\n\x06\x43ircle\x12\x0e\n\x06radius\x18\x01 \x01(\x02\x12\x1d\n\x03\x63tr\x18\x02 \x01(\x0b\x32\x10.vsg.Coordinates\"H\n\x05\x43ross\x12\x0c\n\x04size\x18\x01 \x01(\x02\x12\x12\n\nline_width\x18\x02 \x01(\x02\x12\x1d\n\x03\x63tr\x18\x03 \x01(\x0b\x32\x10.vsg.CoordinatesB\x19\n\nvsg.shapesB\tVsgShapesP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shapes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\nvsg.shapesB\tVsgShapesP\001'
  _SHAPE._serialized_start=21
  _SHAPE._serialized_end=128
  _COORDINATES._serialized_start=130
  _COORDINATES._serialized_end=165
  _SQUARE._serialized_start=167
  _SQUARE._serialized_end=220
  _CIRCLE._serialized_start=222
  _CIRCLE._serialized_end=277
  _CROSS._serialized_start=279
  _CROSS._serialized_end=351
# @@protoc_insertion_point(module_scope)
