// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

public interface BgColorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vsg.BgColor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float color = 1;</code>
   * @return A list containing the color.
   */
  java.util.List<java.lang.Float> getColorList();
  /**
   * <code>repeated float color = 1;</code>
   * @return The count of color.
   */
  int getColorCount();
  /**
   * <code>repeated float color = 1;</code>
   * @param index The index of the element to return.
   * @return The color at the given index.
   */
  float getColor(int index);
}
