// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

public interface CoordinatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vsg.Coordinates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x = 1;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 2;</code>
   * @return The y.
   */
  float getY();
}
