// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

/**
 * Protobuf type {@code vsg.RootMessage}
 */
public final class RootMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vsg.RootMessage)
    RootMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RootMessage.newBuilder() to construct.
  private RootMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RootMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RootMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RootMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            vsg.shapes.Shape.Builder subBuilder = null;
            if (commandCase_ == 1) {
              subBuilder = ((vsg.shapes.Shape) command_).toBuilder();
            }
            command_ =
                input.readMessage(vsg.shapes.Shape.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((vsg.shapes.Shape) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 1;
            break;
          }
          case 18: {
            vsg.BgColor.Builder subBuilder = null;
            if (commandCase_ == 2) {
              subBuilder = ((vsg.BgColor) command_).toBuilder();
            }
            command_ =
                input.readMessage(vsg.BgColor.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((vsg.BgColor) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 2;
            break;
          }
          case 26: {
            vsg.Texture.Builder subBuilder = null;
            if (commandCase_ == 3) {
              subBuilder = ((vsg.Texture) command_).toBuilder();
            }
            command_ =
                input.readMessage(vsg.Texture.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((vsg.Texture) command_);
              command_ = subBuilder.buildPartial();
            }
            commandCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vsg.Vsg.internal_static_vsg_RootMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vsg.Vsg.internal_static_vsg_RootMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vsg.RootMessage.class, vsg.RootMessage.Builder.class);
  }

  private int commandCase_ = 0;
  private java.lang.Object command_;
  public enum CommandCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SET_SHAPE(1),
    SET_BG_COLOR(2),
    SET_TEXTURE(3),
    COMMAND_NOT_SET(0);
    private final int value;
    private CommandCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandCase valueOf(int value) {
      return forNumber(value);
    }

    public static CommandCase forNumber(int value) {
      switch (value) {
        case 1: return SET_SHAPE;
        case 2: return SET_BG_COLOR;
        case 3: return SET_TEXTURE;
        case 0: return COMMAND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CommandCase
  getCommandCase() {
    return CommandCase.forNumber(
        commandCase_);
  }

  public static final int SET_SHAPE_FIELD_NUMBER = 1;
  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   * @return Whether the setShape field is set.
   */
  @java.lang.Override
  public boolean hasSetShape() {
    return commandCase_ == 1;
  }
  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   * @return The setShape.
   */
  @java.lang.Override
  public vsg.shapes.Shape getSetShape() {
    if (commandCase_ == 1) {
       return (vsg.shapes.Shape) command_;
    }
    return vsg.shapes.Shape.getDefaultInstance();
  }
  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   */
  @java.lang.Override
  public vsg.shapes.ShapeOrBuilder getSetShapeOrBuilder() {
    if (commandCase_ == 1) {
       return (vsg.shapes.Shape) command_;
    }
    return vsg.shapes.Shape.getDefaultInstance();
  }

  public static final int SET_BG_COLOR_FIELD_NUMBER = 2;
  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   * @return Whether the setBgColor field is set.
   */
  @java.lang.Override
  public boolean hasSetBgColor() {
    return commandCase_ == 2;
  }
  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   * @return The setBgColor.
   */
  @java.lang.Override
  public vsg.BgColor getSetBgColor() {
    if (commandCase_ == 2) {
       return (vsg.BgColor) command_;
    }
    return vsg.BgColor.getDefaultInstance();
  }
  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   */
  @java.lang.Override
  public vsg.BgColorOrBuilder getSetBgColorOrBuilder() {
    if (commandCase_ == 2) {
       return (vsg.BgColor) command_;
    }
    return vsg.BgColor.getDefaultInstance();
  }

  public static final int SET_TEXTURE_FIELD_NUMBER = 3;
  /**
   * <code>.vsg.Texture set_texture = 3;</code>
   * @return Whether the setTexture field is set.
   */
  @java.lang.Override
  public boolean hasSetTexture() {
    return commandCase_ == 3;
  }
  /**
   * <code>.vsg.Texture set_texture = 3;</code>
   * @return The setTexture.
   */
  @java.lang.Override
  public vsg.Texture getSetTexture() {
    if (commandCase_ == 3) {
       return (vsg.Texture) command_;
    }
    return vsg.Texture.getDefaultInstance();
  }
  /**
   * <code>.vsg.Texture set_texture = 3;</code>
   */
  @java.lang.Override
  public vsg.TextureOrBuilder getSetTextureOrBuilder() {
    if (commandCase_ == 3) {
       return (vsg.Texture) command_;
    }
    return vsg.Texture.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (commandCase_ == 1) {
      output.writeMessage(1, (vsg.shapes.Shape) command_);
    }
    if (commandCase_ == 2) {
      output.writeMessage(2, (vsg.BgColor) command_);
    }
    if (commandCase_ == 3) {
      output.writeMessage(3, (vsg.Texture) command_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (commandCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (vsg.shapes.Shape) command_);
    }
    if (commandCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (vsg.BgColor) command_);
    }
    if (commandCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (vsg.Texture) command_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vsg.RootMessage)) {
      return super.equals(obj);
    }
    vsg.RootMessage other = (vsg.RootMessage) obj;

    if (!getCommandCase().equals(other.getCommandCase())) return false;
    switch (commandCase_) {
      case 1:
        if (!getSetShape()
            .equals(other.getSetShape())) return false;
        break;
      case 2:
        if (!getSetBgColor()
            .equals(other.getSetBgColor())) return false;
        break;
      case 3:
        if (!getSetTexture()
            .equals(other.getSetTexture())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (commandCase_) {
      case 1:
        hash = (37 * hash) + SET_SHAPE_FIELD_NUMBER;
        hash = (53 * hash) + getSetShape().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SET_BG_COLOR_FIELD_NUMBER;
        hash = (53 * hash) + getSetBgColor().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SET_TEXTURE_FIELD_NUMBER;
        hash = (53 * hash) + getSetTexture().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vsg.RootMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.RootMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.RootMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.RootMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.RootMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.RootMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.RootMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vsg.RootMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vsg.RootMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vsg.RootMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vsg.RootMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vsg.RootMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vsg.RootMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vsg.RootMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vsg.RootMessage)
      vsg.RootMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vsg.Vsg.internal_static_vsg_RootMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vsg.Vsg.internal_static_vsg_RootMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vsg.RootMessage.class, vsg.RootMessage.Builder.class);
    }

    // Construct using vsg.RootMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      commandCase_ = 0;
      command_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vsg.Vsg.internal_static_vsg_RootMessage_descriptor;
    }

    @java.lang.Override
    public vsg.RootMessage getDefaultInstanceForType() {
      return vsg.RootMessage.getDefaultInstance();
    }

    @java.lang.Override
    public vsg.RootMessage build() {
      vsg.RootMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vsg.RootMessage buildPartial() {
      vsg.RootMessage result = new vsg.RootMessage(this);
      if (commandCase_ == 1) {
        if (setShapeBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = setShapeBuilder_.build();
        }
      }
      if (commandCase_ == 2) {
        if (setBgColorBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = setBgColorBuilder_.build();
        }
      }
      if (commandCase_ == 3) {
        if (setTextureBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = setTextureBuilder_.build();
        }
      }
      result.commandCase_ = commandCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vsg.RootMessage) {
        return mergeFrom((vsg.RootMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vsg.RootMessage other) {
      if (other == vsg.RootMessage.getDefaultInstance()) return this;
      switch (other.getCommandCase()) {
        case SET_SHAPE: {
          mergeSetShape(other.getSetShape());
          break;
        }
        case SET_BG_COLOR: {
          mergeSetBgColor(other.getSetBgColor());
          break;
        }
        case SET_TEXTURE: {
          mergeSetTexture(other.getSetTexture());
          break;
        }
        case COMMAND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      vsg.RootMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (vsg.RootMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int commandCase_ = 0;
    private java.lang.Object command_;
    public CommandCase
        getCommandCase() {
      return CommandCase.forNumber(
          commandCase_);
    }

    public Builder clearCommand() {
      commandCase_ = 0;
      command_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.shapes.Shape, vsg.shapes.Shape.Builder, vsg.shapes.ShapeOrBuilder> setShapeBuilder_;
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     * @return Whether the setShape field is set.
     */
    @java.lang.Override
    public boolean hasSetShape() {
      return commandCase_ == 1;
    }
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     * @return The setShape.
     */
    @java.lang.Override
    public vsg.shapes.Shape getSetShape() {
      if (setShapeBuilder_ == null) {
        if (commandCase_ == 1) {
          return (vsg.shapes.Shape) command_;
        }
        return vsg.shapes.Shape.getDefaultInstance();
      } else {
        if (commandCase_ == 1) {
          return setShapeBuilder_.getMessage();
        }
        return vsg.shapes.Shape.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     */
    public Builder setSetShape(vsg.shapes.Shape value) {
      if (setShapeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        setShapeBuilder_.setMessage(value);
      }
      commandCase_ = 1;
      return this;
    }
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     */
    public Builder setSetShape(
        vsg.shapes.Shape.Builder builderForValue) {
      if (setShapeBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        setShapeBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 1;
      return this;
    }
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     */
    public Builder mergeSetShape(vsg.shapes.Shape value) {
      if (setShapeBuilder_ == null) {
        if (commandCase_ == 1 &&
            command_ != vsg.shapes.Shape.getDefaultInstance()) {
          command_ = vsg.shapes.Shape.newBuilder((vsg.shapes.Shape) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 1) {
          setShapeBuilder_.mergeFrom(value);
        }
        setShapeBuilder_.setMessage(value);
      }
      commandCase_ = 1;
      return this;
    }
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     */
    public Builder clearSetShape() {
      if (setShapeBuilder_ == null) {
        if (commandCase_ == 1) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 1) {
          commandCase_ = 0;
          command_ = null;
        }
        setShapeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     */
    public vsg.shapes.Shape.Builder getSetShapeBuilder() {
      return getSetShapeFieldBuilder().getBuilder();
    }
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     */
    @java.lang.Override
    public vsg.shapes.ShapeOrBuilder getSetShapeOrBuilder() {
      if ((commandCase_ == 1) && (setShapeBuilder_ != null)) {
        return setShapeBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 1) {
          return (vsg.shapes.Shape) command_;
        }
        return vsg.shapes.Shape.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Shape set_shape = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.shapes.Shape, vsg.shapes.Shape.Builder, vsg.shapes.ShapeOrBuilder> 
        getSetShapeFieldBuilder() {
      if (setShapeBuilder_ == null) {
        if (!(commandCase_ == 1)) {
          command_ = vsg.shapes.Shape.getDefaultInstance();
        }
        setShapeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vsg.shapes.Shape, vsg.shapes.Shape.Builder, vsg.shapes.ShapeOrBuilder>(
                (vsg.shapes.Shape) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 1;
      onChanged();;
      return setShapeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.BgColor, vsg.BgColor.Builder, vsg.BgColorOrBuilder> setBgColorBuilder_;
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     * @return Whether the setBgColor field is set.
     */
    @java.lang.Override
    public boolean hasSetBgColor() {
      return commandCase_ == 2;
    }
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     * @return The setBgColor.
     */
    @java.lang.Override
    public vsg.BgColor getSetBgColor() {
      if (setBgColorBuilder_ == null) {
        if (commandCase_ == 2) {
          return (vsg.BgColor) command_;
        }
        return vsg.BgColor.getDefaultInstance();
      } else {
        if (commandCase_ == 2) {
          return setBgColorBuilder_.getMessage();
        }
        return vsg.BgColor.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     */
    public Builder setSetBgColor(vsg.BgColor value) {
      if (setBgColorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        setBgColorBuilder_.setMessage(value);
      }
      commandCase_ = 2;
      return this;
    }
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     */
    public Builder setSetBgColor(
        vsg.BgColor.Builder builderForValue) {
      if (setBgColorBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        setBgColorBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 2;
      return this;
    }
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     */
    public Builder mergeSetBgColor(vsg.BgColor value) {
      if (setBgColorBuilder_ == null) {
        if (commandCase_ == 2 &&
            command_ != vsg.BgColor.getDefaultInstance()) {
          command_ = vsg.BgColor.newBuilder((vsg.BgColor) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 2) {
          setBgColorBuilder_.mergeFrom(value);
        }
        setBgColorBuilder_.setMessage(value);
      }
      commandCase_ = 2;
      return this;
    }
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     */
    public Builder clearSetBgColor() {
      if (setBgColorBuilder_ == null) {
        if (commandCase_ == 2) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 2) {
          commandCase_ = 0;
          command_ = null;
        }
        setBgColorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     */
    public vsg.BgColor.Builder getSetBgColorBuilder() {
      return getSetBgColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     */
    @java.lang.Override
    public vsg.BgColorOrBuilder getSetBgColorOrBuilder() {
      if ((commandCase_ == 2) && (setBgColorBuilder_ != null)) {
        return setBgColorBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 2) {
          return (vsg.BgColor) command_;
        }
        return vsg.BgColor.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.BgColor set_bg_color = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.BgColor, vsg.BgColor.Builder, vsg.BgColorOrBuilder> 
        getSetBgColorFieldBuilder() {
      if (setBgColorBuilder_ == null) {
        if (!(commandCase_ == 2)) {
          command_ = vsg.BgColor.getDefaultInstance();
        }
        setBgColorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vsg.BgColor, vsg.BgColor.Builder, vsg.BgColorOrBuilder>(
                (vsg.BgColor) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 2;
      onChanged();;
      return setBgColorBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Texture, vsg.Texture.Builder, vsg.TextureOrBuilder> setTextureBuilder_;
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     * @return Whether the setTexture field is set.
     */
    @java.lang.Override
    public boolean hasSetTexture() {
      return commandCase_ == 3;
    }
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     * @return The setTexture.
     */
    @java.lang.Override
    public vsg.Texture getSetTexture() {
      if (setTextureBuilder_ == null) {
        if (commandCase_ == 3) {
          return (vsg.Texture) command_;
        }
        return vsg.Texture.getDefaultInstance();
      } else {
        if (commandCase_ == 3) {
          return setTextureBuilder_.getMessage();
        }
        return vsg.Texture.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     */
    public Builder setSetTexture(vsg.Texture value) {
      if (setTextureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        command_ = value;
        onChanged();
      } else {
        setTextureBuilder_.setMessage(value);
      }
      commandCase_ = 3;
      return this;
    }
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     */
    public Builder setSetTexture(
        vsg.Texture.Builder builderForValue) {
      if (setTextureBuilder_ == null) {
        command_ = builderForValue.build();
        onChanged();
      } else {
        setTextureBuilder_.setMessage(builderForValue.build());
      }
      commandCase_ = 3;
      return this;
    }
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     */
    public Builder mergeSetTexture(vsg.Texture value) {
      if (setTextureBuilder_ == null) {
        if (commandCase_ == 3 &&
            command_ != vsg.Texture.getDefaultInstance()) {
          command_ = vsg.Texture.newBuilder((vsg.Texture) command_)
              .mergeFrom(value).buildPartial();
        } else {
          command_ = value;
        }
        onChanged();
      } else {
        if (commandCase_ == 3) {
          setTextureBuilder_.mergeFrom(value);
        }
        setTextureBuilder_.setMessage(value);
      }
      commandCase_ = 3;
      return this;
    }
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     */
    public Builder clearSetTexture() {
      if (setTextureBuilder_ == null) {
        if (commandCase_ == 3) {
          commandCase_ = 0;
          command_ = null;
          onChanged();
        }
      } else {
        if (commandCase_ == 3) {
          commandCase_ = 0;
          command_ = null;
        }
        setTextureBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     */
    public vsg.Texture.Builder getSetTextureBuilder() {
      return getSetTextureFieldBuilder().getBuilder();
    }
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     */
    @java.lang.Override
    public vsg.TextureOrBuilder getSetTextureOrBuilder() {
      if ((commandCase_ == 3) && (setTextureBuilder_ != null)) {
        return setTextureBuilder_.getMessageOrBuilder();
      } else {
        if (commandCase_ == 3) {
          return (vsg.Texture) command_;
        }
        return vsg.Texture.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Texture set_texture = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Texture, vsg.Texture.Builder, vsg.TextureOrBuilder> 
        getSetTextureFieldBuilder() {
      if (setTextureBuilder_ == null) {
        if (!(commandCase_ == 3)) {
          command_ = vsg.Texture.getDefaultInstance();
        }
        setTextureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vsg.Texture, vsg.Texture.Builder, vsg.TextureOrBuilder>(
                (vsg.Texture) command_,
                getParentForChildren(),
                isClean());
        command_ = null;
      }
      commandCase_ = 3;
      onChanged();;
      return setTextureBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vsg.RootMessage)
  }

  // @@protoc_insertion_point(class_scope:vsg.RootMessage)
  private static final vsg.RootMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vsg.RootMessage();
  }

  public static vsg.RootMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RootMessage>
      PARSER = new com.google.protobuf.AbstractParser<RootMessage>() {
    @java.lang.Override
    public RootMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RootMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RootMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RootMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vsg.RootMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

