// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

public interface RootMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vsg.RootMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   * @return Whether the setShape field is set.
   */
  boolean hasSetShape();
  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   * @return The setShape.
   */
  vsg.shapes.Shape getSetShape();
  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   */
  vsg.shapes.ShapeOrBuilder getSetShapeOrBuilder();

  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   * @return Whether the setBgColor field is set.
   */
  boolean hasSetBgColor();
  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   * @return The setBgColor.
   */
  vsg.BgColor getSetBgColor();
  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   */
  vsg.BgColorOrBuilder getSetBgColorOrBuilder();

  /**
   * <code>.vsg.Texture set_texture = 3;</code>
   * @return Whether the setTexture field is set.
   */
  boolean hasSetTexture();
  /**
   * <code>.vsg.Texture set_texture = 3;</code>
   * @return The setTexture.
   */
  vsg.Texture getSetTexture();
  /**
   * <code>.vsg.Texture set_texture = 3;</code>
   */
  vsg.TextureOrBuilder getSetTextureOrBuilder();

  public vsg.RootMessage.CommandCase getCommandCase();
}
