// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

public interface SetMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vsg.SetMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   * @return Whether the setShape field is set.
   */
  boolean hasSetShape();
  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   * @return The setShape.
   */
  vsg.Shape getSetShape();
  /**
   * <code>.vsg.Shape set_shape = 1;</code>
   */
  vsg.ShapeOrBuilder getSetShapeOrBuilder();

  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   * @return Whether the setBgColor field is set.
   */
  boolean hasSetBgColor();
  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   * @return The setBgColor.
   */
  vsg.BgColor getSetBgColor();
  /**
   * <code>.vsg.BgColor set_bg_color = 2;</code>
   */
  vsg.BgColorOrBuilder getSetBgColorOrBuilder();

  public vsg.SetMessage.CommandCase getCommandCase();
}
