// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

public interface ShapeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vsg.Shape)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.vsg.Square square = 1;</code>
   * @return Whether the square field is set.
   */
  boolean hasSquare();
  /**
   * <code>.vsg.Square square = 1;</code>
   * @return The square.
   */
  vsg.Square getSquare();
  /**
   * <code>.vsg.Square square = 1;</code>
   */
  vsg.SquareOrBuilder getSquareOrBuilder();

  /**
   * <code>.vsg.Circle circle = 2;</code>
   * @return Whether the circle field is set.
   */
  boolean hasCircle();
  /**
   * <code>.vsg.Circle circle = 2;</code>
   * @return The circle.
   */
  vsg.Circle getCircle();
  /**
   * <code>.vsg.Circle circle = 2;</code>
   */
  vsg.CircleOrBuilder getCircleOrBuilder();

  /**
   * <code>.vsg.Cross cross = 3;</code>
   * @return Whether the cross field is set.
   */
  boolean hasCross();
  /**
   * <code>.vsg.Cross cross = 3;</code>
   * @return The cross.
   */
  vsg.Cross getCross();
  /**
   * <code>.vsg.Cross cross = 3;</code>
   */
  vsg.CrossOrBuilder getCrossOrBuilder();

  public vsg.Shape.ShapeCase getShapeCase();
}
