// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

/**
 * Protobuf type {@code vsg.Shape}
 */
public final class Shape extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vsg.Shape)
    ShapeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Shape.newBuilder() to construct.
  private Shape(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Shape() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Shape();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Shape(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            vsg.Square.Builder subBuilder = null;
            if (shapeCase_ == 1) {
              subBuilder = ((vsg.Square) shape_).toBuilder();
            }
            shape_ =
                input.readMessage(vsg.Square.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((vsg.Square) shape_);
              shape_ = subBuilder.buildPartial();
            }
            shapeCase_ = 1;
            break;
          }
          case 18: {
            vsg.Circle.Builder subBuilder = null;
            if (shapeCase_ == 2) {
              subBuilder = ((vsg.Circle) shape_).toBuilder();
            }
            shape_ =
                input.readMessage(vsg.Circle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((vsg.Circle) shape_);
              shape_ = subBuilder.buildPartial();
            }
            shapeCase_ = 2;
            break;
          }
          case 26: {
            vsg.Cross.Builder subBuilder = null;
            if (shapeCase_ == 3) {
              subBuilder = ((vsg.Cross) shape_).toBuilder();
            }
            shape_ =
                input.readMessage(vsg.Cross.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((vsg.Cross) shape_);
              shape_ = subBuilder.buildPartial();
            }
            shapeCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vsg.Vsg.internal_static_vsg_Shape_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vsg.Vsg.internal_static_vsg_Shape_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vsg.Shape.class, vsg.Shape.Builder.class);
  }

  private int shapeCase_ = 0;
  private java.lang.Object shape_;
  public enum ShapeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SQUARE(1),
    CIRCLE(2),
    CROSS(3),
    SHAPE_NOT_SET(0);
    private final int value;
    private ShapeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ShapeCase valueOf(int value) {
      return forNumber(value);
    }

    public static ShapeCase forNumber(int value) {
      switch (value) {
        case 1: return SQUARE;
        case 2: return CIRCLE;
        case 3: return CROSS;
        case 0: return SHAPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ShapeCase
  getShapeCase() {
    return ShapeCase.forNumber(
        shapeCase_);
  }

  public static final int SQUARE_FIELD_NUMBER = 1;
  /**
   * <code>.vsg.Square square = 1;</code>
   * @return Whether the square field is set.
   */
  @java.lang.Override
  public boolean hasSquare() {
    return shapeCase_ == 1;
  }
  /**
   * <code>.vsg.Square square = 1;</code>
   * @return The square.
   */
  @java.lang.Override
  public vsg.Square getSquare() {
    if (shapeCase_ == 1) {
       return (vsg.Square) shape_;
    }
    return vsg.Square.getDefaultInstance();
  }
  /**
   * <code>.vsg.Square square = 1;</code>
   */
  @java.lang.Override
  public vsg.SquareOrBuilder getSquareOrBuilder() {
    if (shapeCase_ == 1) {
       return (vsg.Square) shape_;
    }
    return vsg.Square.getDefaultInstance();
  }

  public static final int CIRCLE_FIELD_NUMBER = 2;
  /**
   * <code>.vsg.Circle circle = 2;</code>
   * @return Whether the circle field is set.
   */
  @java.lang.Override
  public boolean hasCircle() {
    return shapeCase_ == 2;
  }
  /**
   * <code>.vsg.Circle circle = 2;</code>
   * @return The circle.
   */
  @java.lang.Override
  public vsg.Circle getCircle() {
    if (shapeCase_ == 2) {
       return (vsg.Circle) shape_;
    }
    return vsg.Circle.getDefaultInstance();
  }
  /**
   * <code>.vsg.Circle circle = 2;</code>
   */
  @java.lang.Override
  public vsg.CircleOrBuilder getCircleOrBuilder() {
    if (shapeCase_ == 2) {
       return (vsg.Circle) shape_;
    }
    return vsg.Circle.getDefaultInstance();
  }

  public static final int CROSS_FIELD_NUMBER = 3;
  /**
   * <code>.vsg.Cross cross = 3;</code>
   * @return Whether the cross field is set.
   */
  @java.lang.Override
  public boolean hasCross() {
    return shapeCase_ == 3;
  }
  /**
   * <code>.vsg.Cross cross = 3;</code>
   * @return The cross.
   */
  @java.lang.Override
  public vsg.Cross getCross() {
    if (shapeCase_ == 3) {
       return (vsg.Cross) shape_;
    }
    return vsg.Cross.getDefaultInstance();
  }
  /**
   * <code>.vsg.Cross cross = 3;</code>
   */
  @java.lang.Override
  public vsg.CrossOrBuilder getCrossOrBuilder() {
    if (shapeCase_ == 3) {
       return (vsg.Cross) shape_;
    }
    return vsg.Cross.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (shapeCase_ == 1) {
      output.writeMessage(1, (vsg.Square) shape_);
    }
    if (shapeCase_ == 2) {
      output.writeMessage(2, (vsg.Circle) shape_);
    }
    if (shapeCase_ == 3) {
      output.writeMessage(3, (vsg.Cross) shape_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (shapeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (vsg.Square) shape_);
    }
    if (shapeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (vsg.Circle) shape_);
    }
    if (shapeCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (vsg.Cross) shape_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vsg.Shape)) {
      return super.equals(obj);
    }
    vsg.Shape other = (vsg.Shape) obj;

    if (!getShapeCase().equals(other.getShapeCase())) return false;
    switch (shapeCase_) {
      case 1:
        if (!getSquare()
            .equals(other.getSquare())) return false;
        break;
      case 2:
        if (!getCircle()
            .equals(other.getCircle())) return false;
        break;
      case 3:
        if (!getCross()
            .equals(other.getCross())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (shapeCase_) {
      case 1:
        hash = (37 * hash) + SQUARE_FIELD_NUMBER;
        hash = (53 * hash) + getSquare().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CIRCLE_FIELD_NUMBER;
        hash = (53 * hash) + getCircle().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CROSS_FIELD_NUMBER;
        hash = (53 * hash) + getCross().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vsg.Shape parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.Shape parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.Shape parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.Shape parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.Shape parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.Shape parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.Shape parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vsg.Shape parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vsg.Shape parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vsg.Shape parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vsg.Shape parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vsg.Shape parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vsg.Shape prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vsg.Shape}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vsg.Shape)
      vsg.ShapeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vsg.Vsg.internal_static_vsg_Shape_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vsg.Vsg.internal_static_vsg_Shape_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vsg.Shape.class, vsg.Shape.Builder.class);
    }

    // Construct using vsg.Shape.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      shapeCase_ = 0;
      shape_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vsg.Vsg.internal_static_vsg_Shape_descriptor;
    }

    @java.lang.Override
    public vsg.Shape getDefaultInstanceForType() {
      return vsg.Shape.getDefaultInstance();
    }

    @java.lang.Override
    public vsg.Shape build() {
      vsg.Shape result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vsg.Shape buildPartial() {
      vsg.Shape result = new vsg.Shape(this);
      if (shapeCase_ == 1) {
        if (squareBuilder_ == null) {
          result.shape_ = shape_;
        } else {
          result.shape_ = squareBuilder_.build();
        }
      }
      if (shapeCase_ == 2) {
        if (circleBuilder_ == null) {
          result.shape_ = shape_;
        } else {
          result.shape_ = circleBuilder_.build();
        }
      }
      if (shapeCase_ == 3) {
        if (crossBuilder_ == null) {
          result.shape_ = shape_;
        } else {
          result.shape_ = crossBuilder_.build();
        }
      }
      result.shapeCase_ = shapeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vsg.Shape) {
        return mergeFrom((vsg.Shape)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vsg.Shape other) {
      if (other == vsg.Shape.getDefaultInstance()) return this;
      switch (other.getShapeCase()) {
        case SQUARE: {
          mergeSquare(other.getSquare());
          break;
        }
        case CIRCLE: {
          mergeCircle(other.getCircle());
          break;
        }
        case CROSS: {
          mergeCross(other.getCross());
          break;
        }
        case SHAPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      vsg.Shape parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (vsg.Shape) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int shapeCase_ = 0;
    private java.lang.Object shape_;
    public ShapeCase
        getShapeCase() {
      return ShapeCase.forNumber(
          shapeCase_);
    }

    public Builder clearShape() {
      shapeCase_ = 0;
      shape_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Square, vsg.Square.Builder, vsg.SquareOrBuilder> squareBuilder_;
    /**
     * <code>.vsg.Square square = 1;</code>
     * @return Whether the square field is set.
     */
    @java.lang.Override
    public boolean hasSquare() {
      return shapeCase_ == 1;
    }
    /**
     * <code>.vsg.Square square = 1;</code>
     * @return The square.
     */
    @java.lang.Override
    public vsg.Square getSquare() {
      if (squareBuilder_ == null) {
        if (shapeCase_ == 1) {
          return (vsg.Square) shape_;
        }
        return vsg.Square.getDefaultInstance();
      } else {
        if (shapeCase_ == 1) {
          return squareBuilder_.getMessage();
        }
        return vsg.Square.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Square square = 1;</code>
     */
    public Builder setSquare(vsg.Square value) {
      if (squareBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shape_ = value;
        onChanged();
      } else {
        squareBuilder_.setMessage(value);
      }
      shapeCase_ = 1;
      return this;
    }
    /**
     * <code>.vsg.Square square = 1;</code>
     */
    public Builder setSquare(
        vsg.Square.Builder builderForValue) {
      if (squareBuilder_ == null) {
        shape_ = builderForValue.build();
        onChanged();
      } else {
        squareBuilder_.setMessage(builderForValue.build());
      }
      shapeCase_ = 1;
      return this;
    }
    /**
     * <code>.vsg.Square square = 1;</code>
     */
    public Builder mergeSquare(vsg.Square value) {
      if (squareBuilder_ == null) {
        if (shapeCase_ == 1 &&
            shape_ != vsg.Square.getDefaultInstance()) {
          shape_ = vsg.Square.newBuilder((vsg.Square) shape_)
              .mergeFrom(value).buildPartial();
        } else {
          shape_ = value;
        }
        onChanged();
      } else {
        if (shapeCase_ == 1) {
          squareBuilder_.mergeFrom(value);
        }
        squareBuilder_.setMessage(value);
      }
      shapeCase_ = 1;
      return this;
    }
    /**
     * <code>.vsg.Square square = 1;</code>
     */
    public Builder clearSquare() {
      if (squareBuilder_ == null) {
        if (shapeCase_ == 1) {
          shapeCase_ = 0;
          shape_ = null;
          onChanged();
        }
      } else {
        if (shapeCase_ == 1) {
          shapeCase_ = 0;
          shape_ = null;
        }
        squareBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.vsg.Square square = 1;</code>
     */
    public vsg.Square.Builder getSquareBuilder() {
      return getSquareFieldBuilder().getBuilder();
    }
    /**
     * <code>.vsg.Square square = 1;</code>
     */
    @java.lang.Override
    public vsg.SquareOrBuilder getSquareOrBuilder() {
      if ((shapeCase_ == 1) && (squareBuilder_ != null)) {
        return squareBuilder_.getMessageOrBuilder();
      } else {
        if (shapeCase_ == 1) {
          return (vsg.Square) shape_;
        }
        return vsg.Square.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Square square = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Square, vsg.Square.Builder, vsg.SquareOrBuilder> 
        getSquareFieldBuilder() {
      if (squareBuilder_ == null) {
        if (!(shapeCase_ == 1)) {
          shape_ = vsg.Square.getDefaultInstance();
        }
        squareBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vsg.Square, vsg.Square.Builder, vsg.SquareOrBuilder>(
                (vsg.Square) shape_,
                getParentForChildren(),
                isClean());
        shape_ = null;
      }
      shapeCase_ = 1;
      onChanged();;
      return squareBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Circle, vsg.Circle.Builder, vsg.CircleOrBuilder> circleBuilder_;
    /**
     * <code>.vsg.Circle circle = 2;</code>
     * @return Whether the circle field is set.
     */
    @java.lang.Override
    public boolean hasCircle() {
      return shapeCase_ == 2;
    }
    /**
     * <code>.vsg.Circle circle = 2;</code>
     * @return The circle.
     */
    @java.lang.Override
    public vsg.Circle getCircle() {
      if (circleBuilder_ == null) {
        if (shapeCase_ == 2) {
          return (vsg.Circle) shape_;
        }
        return vsg.Circle.getDefaultInstance();
      } else {
        if (shapeCase_ == 2) {
          return circleBuilder_.getMessage();
        }
        return vsg.Circle.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Circle circle = 2;</code>
     */
    public Builder setCircle(vsg.Circle value) {
      if (circleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shape_ = value;
        onChanged();
      } else {
        circleBuilder_.setMessage(value);
      }
      shapeCase_ = 2;
      return this;
    }
    /**
     * <code>.vsg.Circle circle = 2;</code>
     */
    public Builder setCircle(
        vsg.Circle.Builder builderForValue) {
      if (circleBuilder_ == null) {
        shape_ = builderForValue.build();
        onChanged();
      } else {
        circleBuilder_.setMessage(builderForValue.build());
      }
      shapeCase_ = 2;
      return this;
    }
    /**
     * <code>.vsg.Circle circle = 2;</code>
     */
    public Builder mergeCircle(vsg.Circle value) {
      if (circleBuilder_ == null) {
        if (shapeCase_ == 2 &&
            shape_ != vsg.Circle.getDefaultInstance()) {
          shape_ = vsg.Circle.newBuilder((vsg.Circle) shape_)
              .mergeFrom(value).buildPartial();
        } else {
          shape_ = value;
        }
        onChanged();
      } else {
        if (shapeCase_ == 2) {
          circleBuilder_.mergeFrom(value);
        }
        circleBuilder_.setMessage(value);
      }
      shapeCase_ = 2;
      return this;
    }
    /**
     * <code>.vsg.Circle circle = 2;</code>
     */
    public Builder clearCircle() {
      if (circleBuilder_ == null) {
        if (shapeCase_ == 2) {
          shapeCase_ = 0;
          shape_ = null;
          onChanged();
        }
      } else {
        if (shapeCase_ == 2) {
          shapeCase_ = 0;
          shape_ = null;
        }
        circleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.vsg.Circle circle = 2;</code>
     */
    public vsg.Circle.Builder getCircleBuilder() {
      return getCircleFieldBuilder().getBuilder();
    }
    /**
     * <code>.vsg.Circle circle = 2;</code>
     */
    @java.lang.Override
    public vsg.CircleOrBuilder getCircleOrBuilder() {
      if ((shapeCase_ == 2) && (circleBuilder_ != null)) {
        return circleBuilder_.getMessageOrBuilder();
      } else {
        if (shapeCase_ == 2) {
          return (vsg.Circle) shape_;
        }
        return vsg.Circle.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Circle circle = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Circle, vsg.Circle.Builder, vsg.CircleOrBuilder> 
        getCircleFieldBuilder() {
      if (circleBuilder_ == null) {
        if (!(shapeCase_ == 2)) {
          shape_ = vsg.Circle.getDefaultInstance();
        }
        circleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vsg.Circle, vsg.Circle.Builder, vsg.CircleOrBuilder>(
                (vsg.Circle) shape_,
                getParentForChildren(),
                isClean());
        shape_ = null;
      }
      shapeCase_ = 2;
      onChanged();;
      return circleBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Cross, vsg.Cross.Builder, vsg.CrossOrBuilder> crossBuilder_;
    /**
     * <code>.vsg.Cross cross = 3;</code>
     * @return Whether the cross field is set.
     */
    @java.lang.Override
    public boolean hasCross() {
      return shapeCase_ == 3;
    }
    /**
     * <code>.vsg.Cross cross = 3;</code>
     * @return The cross.
     */
    @java.lang.Override
    public vsg.Cross getCross() {
      if (crossBuilder_ == null) {
        if (shapeCase_ == 3) {
          return (vsg.Cross) shape_;
        }
        return vsg.Cross.getDefaultInstance();
      } else {
        if (shapeCase_ == 3) {
          return crossBuilder_.getMessage();
        }
        return vsg.Cross.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Cross cross = 3;</code>
     */
    public Builder setCross(vsg.Cross value) {
      if (crossBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shape_ = value;
        onChanged();
      } else {
        crossBuilder_.setMessage(value);
      }
      shapeCase_ = 3;
      return this;
    }
    /**
     * <code>.vsg.Cross cross = 3;</code>
     */
    public Builder setCross(
        vsg.Cross.Builder builderForValue) {
      if (crossBuilder_ == null) {
        shape_ = builderForValue.build();
        onChanged();
      } else {
        crossBuilder_.setMessage(builderForValue.build());
      }
      shapeCase_ = 3;
      return this;
    }
    /**
     * <code>.vsg.Cross cross = 3;</code>
     */
    public Builder mergeCross(vsg.Cross value) {
      if (crossBuilder_ == null) {
        if (shapeCase_ == 3 &&
            shape_ != vsg.Cross.getDefaultInstance()) {
          shape_ = vsg.Cross.newBuilder((vsg.Cross) shape_)
              .mergeFrom(value).buildPartial();
        } else {
          shape_ = value;
        }
        onChanged();
      } else {
        if (shapeCase_ == 3) {
          crossBuilder_.mergeFrom(value);
        }
        crossBuilder_.setMessage(value);
      }
      shapeCase_ = 3;
      return this;
    }
    /**
     * <code>.vsg.Cross cross = 3;</code>
     */
    public Builder clearCross() {
      if (crossBuilder_ == null) {
        if (shapeCase_ == 3) {
          shapeCase_ = 0;
          shape_ = null;
          onChanged();
        }
      } else {
        if (shapeCase_ == 3) {
          shapeCase_ = 0;
          shape_ = null;
        }
        crossBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.vsg.Cross cross = 3;</code>
     */
    public vsg.Cross.Builder getCrossBuilder() {
      return getCrossFieldBuilder().getBuilder();
    }
    /**
     * <code>.vsg.Cross cross = 3;</code>
     */
    @java.lang.Override
    public vsg.CrossOrBuilder getCrossOrBuilder() {
      if ((shapeCase_ == 3) && (crossBuilder_ != null)) {
        return crossBuilder_.getMessageOrBuilder();
      } else {
        if (shapeCase_ == 3) {
          return (vsg.Cross) shape_;
        }
        return vsg.Cross.getDefaultInstance();
      }
    }
    /**
     * <code>.vsg.Cross cross = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Cross, vsg.Cross.Builder, vsg.CrossOrBuilder> 
        getCrossFieldBuilder() {
      if (crossBuilder_ == null) {
        if (!(shapeCase_ == 3)) {
          shape_ = vsg.Cross.getDefaultInstance();
        }
        crossBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vsg.Cross, vsg.Cross.Builder, vsg.CrossOrBuilder>(
                (vsg.Cross) shape_,
                getParentForChildren(),
                isClean());
        shape_ = null;
      }
      shapeCase_ = 3;
      onChanged();;
      return crossBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vsg.Shape)
  }

  // @@protoc_insertion_point(class_scope:vsg.Shape)
  private static final vsg.Shape DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vsg.Shape();
  }

  public static vsg.Shape getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Shape>
      PARSER = new com.google.protobuf.AbstractParser<Shape>() {
    @java.lang.Override
    public Shape parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Shape(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Shape> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Shape> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vsg.Shape getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

