// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

/**
 * Protobuf type {@code vsg.Square}
 */
public final class Square extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vsg.Square)
    SquareOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Square.newBuilder() to construct.
  private Square(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Square() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Square();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Square(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            size_ = input.readFloat();
            break;
          }
          case 18: {
            vsg.Coordinates.Builder subBuilder = null;
            if (ctr_ != null) {
              subBuilder = ctr_.toBuilder();
            }
            ctr_ = input.readMessage(vsg.Coordinates.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ctr_);
              ctr_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return vsg.Vsg.internal_static_vsg_Square_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return vsg.Vsg.internal_static_vsg_Square_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            vsg.Square.class, vsg.Square.Builder.class);
  }

  public static final int SIZE_FIELD_NUMBER = 1;
  private float size_;
  /**
   * <code>float size = 1;</code>
   * @return The size.
   */
  @java.lang.Override
  public float getSize() {
    return size_;
  }

  public static final int CTR_FIELD_NUMBER = 2;
  private vsg.Coordinates ctr_;
  /**
   * <code>.vsg.Coordinates ctr = 2;</code>
   * @return Whether the ctr field is set.
   */
  @java.lang.Override
  public boolean hasCtr() {
    return ctr_ != null;
  }
  /**
   * <code>.vsg.Coordinates ctr = 2;</code>
   * @return The ctr.
   */
  @java.lang.Override
  public vsg.Coordinates getCtr() {
    return ctr_ == null ? vsg.Coordinates.getDefaultInstance() : ctr_;
  }
  /**
   * <code>.vsg.Coordinates ctr = 2;</code>
   */
  @java.lang.Override
  public vsg.CoordinatesOrBuilder getCtrOrBuilder() {
    return getCtr();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (size_ != 0F) {
      output.writeFloat(1, size_);
    }
    if (ctr_ != null) {
      output.writeMessage(2, getCtr());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (size_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, size_);
    }
    if (ctr_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCtr());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof vsg.Square)) {
      return super.equals(obj);
    }
    vsg.Square other = (vsg.Square) obj;

    if (java.lang.Float.floatToIntBits(getSize())
        != java.lang.Float.floatToIntBits(
            other.getSize())) return false;
    if (hasCtr() != other.hasCtr()) return false;
    if (hasCtr()) {
      if (!getCtr()
          .equals(other.getCtr())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSize());
    if (hasCtr()) {
      hash = (37 * hash) + CTR_FIELD_NUMBER;
      hash = (53 * hash) + getCtr().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static vsg.Square parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.Square parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.Square parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.Square parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.Square parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static vsg.Square parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static vsg.Square parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vsg.Square parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static vsg.Square parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static vsg.Square parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static vsg.Square parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static vsg.Square parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(vsg.Square prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vsg.Square}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vsg.Square)
      vsg.SquareOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vsg.Vsg.internal_static_vsg_Square_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vsg.Vsg.internal_static_vsg_Square_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vsg.Square.class, vsg.Square.Builder.class);
    }

    // Construct using vsg.Square.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      size_ = 0F;

      if (ctrBuilder_ == null) {
        ctr_ = null;
      } else {
        ctr_ = null;
        ctrBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return vsg.Vsg.internal_static_vsg_Square_descriptor;
    }

    @java.lang.Override
    public vsg.Square getDefaultInstanceForType() {
      return vsg.Square.getDefaultInstance();
    }

    @java.lang.Override
    public vsg.Square build() {
      vsg.Square result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public vsg.Square buildPartial() {
      vsg.Square result = new vsg.Square(this);
      result.size_ = size_;
      if (ctrBuilder_ == null) {
        result.ctr_ = ctr_;
      } else {
        result.ctr_ = ctrBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof vsg.Square) {
        return mergeFrom((vsg.Square)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(vsg.Square other) {
      if (other == vsg.Square.getDefaultInstance()) return this;
      if (other.getSize() != 0F) {
        setSize(other.getSize());
      }
      if (other.hasCtr()) {
        mergeCtr(other.getCtr());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      vsg.Square parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (vsg.Square) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float size_ ;
    /**
     * <code>float size = 1;</code>
     * @return The size.
     */
    @java.lang.Override
    public float getSize() {
      return size_;
    }
    /**
     * <code>float size = 1;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(float value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float size = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = 0F;
      onChanged();
      return this;
    }

    private vsg.Coordinates ctr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Coordinates, vsg.Coordinates.Builder, vsg.CoordinatesOrBuilder> ctrBuilder_;
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     * @return Whether the ctr field is set.
     */
    public boolean hasCtr() {
      return ctrBuilder_ != null || ctr_ != null;
    }
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     * @return The ctr.
     */
    public vsg.Coordinates getCtr() {
      if (ctrBuilder_ == null) {
        return ctr_ == null ? vsg.Coordinates.getDefaultInstance() : ctr_;
      } else {
        return ctrBuilder_.getMessage();
      }
    }
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     */
    public Builder setCtr(vsg.Coordinates value) {
      if (ctrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ctr_ = value;
        onChanged();
      } else {
        ctrBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     */
    public Builder setCtr(
        vsg.Coordinates.Builder builderForValue) {
      if (ctrBuilder_ == null) {
        ctr_ = builderForValue.build();
        onChanged();
      } else {
        ctrBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     */
    public Builder mergeCtr(vsg.Coordinates value) {
      if (ctrBuilder_ == null) {
        if (ctr_ != null) {
          ctr_ =
            vsg.Coordinates.newBuilder(ctr_).mergeFrom(value).buildPartial();
        } else {
          ctr_ = value;
        }
        onChanged();
      } else {
        ctrBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     */
    public Builder clearCtr() {
      if (ctrBuilder_ == null) {
        ctr_ = null;
        onChanged();
      } else {
        ctr_ = null;
        ctrBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     */
    public vsg.Coordinates.Builder getCtrBuilder() {
      
      onChanged();
      return getCtrFieldBuilder().getBuilder();
    }
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     */
    public vsg.CoordinatesOrBuilder getCtrOrBuilder() {
      if (ctrBuilder_ != null) {
        return ctrBuilder_.getMessageOrBuilder();
      } else {
        return ctr_ == null ?
            vsg.Coordinates.getDefaultInstance() : ctr_;
      }
    }
    /**
     * <code>.vsg.Coordinates ctr = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        vsg.Coordinates, vsg.Coordinates.Builder, vsg.CoordinatesOrBuilder> 
        getCtrFieldBuilder() {
      if (ctrBuilder_ == null) {
        ctrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            vsg.Coordinates, vsg.Coordinates.Builder, vsg.CoordinatesOrBuilder>(
                getCtr(),
                getParentForChildren(),
                isClean());
        ctr_ = null;
      }
      return ctrBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vsg.Square)
  }

  // @@protoc_insertion_point(class_scope:vsg.Square)
  private static final vsg.Square DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new vsg.Square();
  }

  public static vsg.Square getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Square>
      PARSER = new com.google.protobuf.AbstractParser<Square>() {
    @java.lang.Override
    public Square parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Square(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Square> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Square> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public vsg.Square getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

