// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package vsg;

public interface TextureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vsg.Texture)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
